on:
  push:
    branches:
    - main
    - master
    - release/*
    - hotfix/*
    - hotfixes/*

defaults:
  run: 
    working-directory: ./

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps: 
    - uses: CultureHQ/actions-yarn@v1.0.1
    - run: yarn install
    - run: yarn test
